basePath: /api/v1
definitions:
  model.LoginRequest:
    properties:
      email:
        maxLength: 100
        type: string
      password:
        maxLength: 255
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  model.Message:
    properties:
      message:
        type: string
    type: object
  model.PageMetadata:
    properties:
      page:
        type: integer
      size:
        type: integer
      total_items:
        type: integer
      total_pages:
        type: integer
    type: object
  model.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  model.RegisterRequest:
    properties:
      email:
        maxLength: 100
        type: string
      password:
        maxLength: 255
        minLength: 8
        type: string
      role:
        enum:
        - admin
        - user
        type: string
    required:
    - email
    - password
    - role
    type: object
  model.Response-any:
    properties:
      data: {}
      message:
        $ref: '#/definitions/model.Message'
      paging:
        $ref: '#/definitions/model.PageMetadata'
    type: object
  model.Response-array_model_TodoResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.TodoResponse'
        type: array
      message:
        $ref: '#/definitions/model.Message'
      paging:
        $ref: '#/definitions/model.PageMetadata'
    type: object
  model.Response-model_TodoResponse:
    properties:
      data:
        $ref: '#/definitions/model.TodoResponse'
      message:
        $ref: '#/definitions/model.Message'
      paging:
        $ref: '#/definitions/model.PageMetadata'
    type: object
  model.Response-model_TokenResponse:
    properties:
      data:
        $ref: '#/definitions/model.TokenResponse'
      message:
        $ref: '#/definitions/model.Message'
      paging:
        $ref: '#/definitions/model.PageMetadata'
    type: object
  model.Response-model_UserResponse:
    properties:
      data:
        $ref: '#/definitions/model.UserResponse'
      message:
        $ref: '#/definitions/model.Message'
      paging:
        $ref: '#/definitions/model.PageMetadata'
    type: object
  model.TodoCreateRequest:
    properties:
      title:
        maxLength: 255
        minLength: 5
        type: string
    required:
    - title
    type: object
  model.TodoResponse:
    properties:
      completed:
        type: boolean
      created_at:
        type: string
      id:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  model.TodoUpdateRequest:
    properties:
      completed:
        type: boolean
      title:
        maxLength: 255
        minLength: 5
        type: string
    type: object
  model.TokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  model.UserResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      role:
        type: string
      status:
        type: boolean
      updated_at:
        type: string
    type: object
info:
  contact:
    email: jakueenak@gmail.com
    name: API Support
  description: This is an auto-generated API Docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Todo API
  version: "0.1"
paths:
  /todo:
    get:
      consumes:
      - application/json
      description: List todo
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Page
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response-array_model_TodoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response-any'
      security:
      - ApiKeyAuth: []
      summary: List todo
      tags:
      - todo
    post:
      consumes:
      - application/json
      description: Create a new todo
      parameters:
      - description: Todo data
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/model.TodoCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Response-model_TodoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response-any'
      security:
      - ApiKeyAuth: []
      summary: Create a new todo
      tags:
      - todo
  /todo/{id}:
    delete:
      consumes:
      - application/json
      description: Delete todo
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response-model_TodoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response-any'
      security:
      - ApiKeyAuth: []
      summary: Delete todo
      tags:
      - todo
    get:
      consumes:
      - application/json
      description: Get todo by ID
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response-model_TodoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response-any'
      security:
      - ApiKeyAuth: []
      summary: Get todo by ID
      tags:
      - todo
    put:
      consumes:
      - application/json
      description: Update todo
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: string
      - description: Todo data
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/model.TodoUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response-model_TodoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response-any'
      security:
      - ApiKeyAuth: []
      summary: Update todo
      tags:
      - todo
  /users:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Response-model_UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response-any'
      summary: Register a new user
      tags:
      - user
  /users/login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response-model_UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response-any'
      summary: Login a user
      tags:
      - user
  /users/refresh:
    post:
      consumes:
      - application/json
      description: Refresh token
      parameters:
      - description: Refresh token data
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/model.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response-model_TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response-any'
      summary: Refresh token
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
